#Config
permalink: /posts/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

#Site
title : Will Greenway
tagline :
production_url : wpgreenway.com

#Author
name : Will Greenway
email : wpgreenway@gmail.com
github : wpgreenway
twitter : wpgreenway
gravatar_url : http://www.gravatar.com/avatar/11cf1eb89be17e14a81d13f49fd05b8b.png

#Analytics
google_tracking_id : UA-38232361-1